### ISSUE TITLE
Represent synodic sites

### ISSUE THREAD

**Issue by nornagon** [nornagon/hf-mission-planner#11]
and, for the HF4 map, other features that depend on the solar season (e.g. the Venus flyby)

**Comment by pvh** [comment]
Is this actually useful? The flyby is, for sure, but synodic sites seem to all just be landing destinations.

**Comment by pvh** [comment]
If it's just the Venus flyby I can create a special-case map node and a fly-by toggle which excludes it (and any edges connecting to it) from the data passed to the dystra code. Or does it exist but not give a bonus off-season?

**Comment by nornagon** [comment]
hm, yeah, probably just the Venus flyby.

I could imagine taking into account added sunspot radiation during whichever bit of the cycle it is that increases the likelihood of radiation damage, but that's probably not so useful.

**Comment by nornagon** [comment]
i... think you can't fly through that node during not-blue season

**Comment by nornagon** [comment]
Fixed by #17
