### ISSUE TITLE
Missing node exit label

### ISSUE THREAD

**Issue by kret** [nornagon/hf-mission-planner#20]
There is a missing exit label on one of the nodes:
<img width="655" alt="hf-planner-exit-node-label" src="https://user-images.githubusercontent.com/73063/86017844-d4ccc500-ba24-11ea-8243-e2ea66c2246a.png">
I guess it should say `2`.

Thanks for the tool!

**Comment by nornagon** [comment]
Eagle eyes! thanks for the report.
