### ISSUE TITLE
venus flyby during other season than blue

### ISSUE THREAD

**Issue by duke164** [nornagon/hf-mission-planner#27]
Hi

the question about how does venus flyby work araised on the BGG forum. And Dom Rougier and Geoff Speare has explained that outside blue season you can go through venus flyby but that point doesn't give you any flybyboost (treating it as a normal lagrange point). look at the discussion on feb, 3 rd about rules clarification.
But , what I've understood from you're planner is that you prohibit its use outside the blue season. So I'm thinking it's a bug.

regards,

**Comment by nornagon** [comment]
ah, ok! makes sense, thanks for the note :)

**Comment by nornagon** [comment]
Belatedly, this is fixed now!
