### ISSUE TITLE
L1 Sol-Earth curve path near Venus

### ISSUE THREAD

**Issue by Luriant** [nornagon/hf-mission-planner#46]
The tool have problems using this path, that wait in this hoffman 1 year before Venus Assist. Maybe the tool ignore this.

Is useful, because blue path and Mars assist could reach a Hoffman point in Jupiter from above, in Turn 3 you can enter jupiter and fly to Hygeia. -1 year than using the Tool (and 4 Rad belts, but Crew Thrusters can be used for speed bonus, the path to Hygeia don't have thrust cost).

This aid pdf include in the 3rd page the same point in the most popular route. https://boardgamegeek.com/filepage/212809/hf4-two-burn-paths

**Comment by nornagon** [comment]
Thanks for the report! Can you please include a screenshot of the path/paths you're talking about?

**Comment by Luriant** [comment]
![Lack of Hoffman](https://user-images.githubusercontent.com/72674159/185249958-232c271c-ea02-400b-9f83-b2e2083a1db3.png)

Green, year 1, two burn outside earth, the end point isn't marked in the mission planner
Blue, year 2, assist, blue path and wait above jupiter
Red, year 3, jupited rad belts, assist, and landing into hygeia

This trip is impossible in the mission planner, because lack 1 hoffman, but very important for venus assist, and easy jupiter assist.

Thanks for your support.

Not related to this bug, The planner freeze or go very slow in firefox, with chrome having normal speed. Any missing library to download?

**Comment by Luriant** [comment]
Any fix for this? I edited the map by myself, but isnt a stable solution.

Also, the new map change Lutetia Mass and ISRU, and added a new comet near Mars.

**Comment by nornagon** [comment]
@Luriant sorry for the long delay, this should be fixed now.

**Comment by nornagon** [comment]
Just realized I hadn't actually deployed the fix 🤦🏻 _now_ it should be fixed!
